### ISSUE TITLE
Robotization Mono line height inconsistent with Roboto Mono

### ISSUE THREAD

**Issue by musm** [kiwi0fruit/open-fonts#16]
Robotization Mono line height inconsistent with Roboto Mono

It is actually more compressed.

**Comment by kiwi0fruit** [comment]
In Ubuntu PyCharm it occupies the exact same XY space as Droid Sans Mono. At the moment I cannot test in other program or vs. another font.

So if it's consistent with itself and DejaVu Sans Mono has the same size when used as fallback then Robotization Mono works as intended.

**Comment by kiwi0fruit** [comment]
Oh. You may actually encountered difference when using it with font (auto?) hinting (default on WIndows). Robitization Mono either can have no hinting (I'm not sure how FontForge handled it as for regular I only used it to rename and set flags so it should not have lost it. Or may it still have) or due to older or newer version have different hinting (but I doubt it).

I have no desire to investigate if that's the case as I never use hinting (both on Linux and on Windows) - I prefer the way MacType on Windows renders fonts.

Hinting doesn't change place the font occupies rounded by pixels but it can distort font letters a lot.

**Comment by musm** [comment]
Well I'm not exactly sure. I was using with the new Windows Terminal, and when I tried to use Robotization Mono the line-height is quite compressed.

**Comment by kiwi0fruit** [comment]
If the issue is with hinting then the font would occupy the same space but letterforms would be distorted and may look compressed. If the issue is not with hinting then the font would occupy different space but look more or less same proportioned (UPD: or even differently-proportioned but part about different space stands).

If the hinting is the issue I can recommend either disabling it via MacType or try [other nice-looking fonts](https://github.com/kiwi0fruit/open-fonts#best-monospace) until they suit your taste.

**Comment by musm** [comment]
Ok thank you!

**Comment by kiwi0fruit** [comment]
More to the picture:

A nice example of hinting design nightmare on Windows can be seen if opening Word <=2007 or any Libre Office and using simple Times New Roman then increasing font size gradually (+1pt) starting from 12pt and seeing how letters proportions change from nice one (in my case it was 12pt) to worse one and again OK ones.

Hinting hammers letters to the pixel grid gaining clarity and sacrificing letter shapes. There a lot of about it on internet: macOS font rendering vs Windows font rendering.

**Comment by kiwi0fruit** [comment]
By the way: the problem is no longer relevant on retina smartphones or 4K monitors.
